// <auto-generated />
namespace proLibManageSys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class forthCreate1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(forthCreate1));
        
        string IMigrationMetadata.Id
        {
            get { return "202011240952387_forthCreate1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
